# Numpy
### Alberto Torres Barrán

Numpy es una libreria fundamental de Python que implementa operaciones con arrays n-dimensionales. Tiene herramientas básicas de álgebra lineal, estadística, generación de número aleatorios, etc. y además es la base de otras librearías como Pandas, Scipy o scikit-learn.    

Referencia: https://docs.scipy.org/doc/numpy-1.9.1/index.html

In [1]:
# Importamos numpy y creamos un ndarray para representar una matriz 3x3:
import numpy as np

# ver version
print(np.version.version)

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

1.18.1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# Algunos atributos de los arrays
print(data.shape)
print(data.dtype)

(3, 3)
int64


Lista completa de métodos y atributos del objeto `ndarray`: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

##### Creación de un array

La función principal es `np.array()`, que crea arrays a partir de secuencias (listas, tuplas, etc.). También existen funciones para crear arrays especiales como arrays vacios, de 0s y de 1s.

Referencias:     
https://docs.scipy.org/doc/numpy-1.9.1/reference/generated/numpy.array.html#numpy.array    
https://docs.scipy.org/doc/numpy-1.9.1/reference/routines.array-creation.html#routines-array-creation

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# el tipo se infiere de los datos
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [5]:
# también se puede especificar
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [6]:
# se pueden crear arrays de mas de 1 dimension
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# y tambien especificar el numero de dimensiones minimo
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

##### Operaciones

Todas las operaciones aritméticas básicas (+, -, /, *) están implementadas para los arrays de numpy. Se aplican elemento a elemento. Por tanto, los arrays tienen que tener el mismo tamaño (salvo algunas excepciones, lo veremos más adelante)

In [8]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [9]:
2 ** a

array([ 2,  4,  8, 16])

In [10]:
b = np.ones(4) + 1
a + b

array([3., 4., 5., 6.])

In [11]:
a / b

array([0.5, 1. , 1.5, 2. ])

In [12]:
# Esta no es la múltiplicación de matrices!!!!
import numpy as np
from numpy import array, arange
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Otras operaciones

Los operadores de comparación también se aplican elemento a elemento.

In [13]:
a = np.array([5, 7, 3, 4])
b = np.array([5, 2, 6, 9])

a > b

array([False,  True, False, False])

In [14]:
a == b

array([ True, False, False, False])

Y también los operadores lógicos, pero no con la sintáxis habitual de Python

In [15]:
c = a > b
d = a == b

np.logical_and(c, d)

array([False, False, False, False])

In [16]:
np.logical_or(c, d)

array([ True,  True, False, False])

Numpy también implementa muchas de funciones matemáticas:

https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [17]:
# funcion seno
np.sin(a)

array([-0.95892427,  0.6569866 ,  0.14112001, -0.7568025 ])

##### Indexación

De forma muy similar a las secuencias en Python, los arrays se pueden indexar con corchetes `[]` y el operador `:`

Si el array tiene múltiples dimensiones, necesitamos un índice por cada una de ellas, separados por comas.

Al igual que las listas los arrays son mutables, es decir, si modificamos los elementos estamos cambiando el array original y no una copia

Referencia: https://docs.scipy.org/doc/numpy/user/basics.indexing.html

In [18]:
x = np.arange(10)
x[2:6]

array([2, 3, 4, 5])

In [19]:
x[8]

8

In [20]:
x[-3:]

array([7, 8, 9])

In [21]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
l = [[1, 2], [3, 4]]

In [23]:
# con arrays multidimensionales es parecido
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
data[2, 3]

12

In [25]:
data[1:4, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

Más ejemplos:

<img src="../img/index.png" alt="Drawing" style="width: 500px;"/>

(Fuente: Scipy lectures)

También se pueden indexar utilizando valores booleanos, donde se seleccionan únicamente aquellos que son `True`.   
Los arrays booleanos de índices tienen que tener el mismo tamaño que lo que estamos indexando. Con esta indexación se crea una copia del array.   

In [26]:
import numpy as np
data = np.random.randn(10, 3)
data

array([[-1.42597456, -0.57255641,  0.83790582],
       [ 1.0943617 ,  0.80581683,  1.70927155],
       [ 1.18626906, -1.08059436, -2.5955867 ],
       [ 0.18822497,  0.44522526, -1.19017704],
       [-0.3406656 ,  0.52179978,  0.43459118],
       [-1.05314645, -0.72051146, -0.69634866],
       [-0.45622233,  0.9132204 , -0.53268403],
       [ 0.27657176,  0.09320174,  1.21616545],
       [ 0.49531176,  0.18362332,  1.23074918],
       [-0.86886025, -0.26970221,  0.30215121]])

In [27]:
data > 0 

array([[False, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True, False],
       [False,  True,  True],
       [False, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [28]:
data[ data > 0 ]

array([0.83790582, 1.0943617 , 0.80581683, 1.70927155, 1.18626906,
       0.18822497, 0.44522526, 0.52179978, 0.43459118, 0.9132204 ,
       0.27657176, 0.09320174, 1.21616545, 0.49531176, 0.18362332,
       1.23074918, 0.30215121])

In [29]:
idx = data[:,0] < 0
idx

array([ True, False, False, False,  True,  True,  True, False, False,
        True])

In [30]:
# filas que en la primera columna tienen un número negativo
data [ idx, : ]

array([[-1.42597456, -0.57255641,  0.83790582],
       [-0.3406656 ,  0.52179978,  0.43459118],
       [-1.05314645, -0.72051146, -0.69634866],
       [-0.45622233,  0.9132204 , -0.53268403],
       [-0.86886025, -0.26970221,  0.30215121]])

Por último, también podemos indexar con secuencias de temaño arbitrario de números enteros.

In [31]:
data[(1, 2), :]

array([[ 1.0943617 ,  0.80581683,  1.70927155],
       [ 1.18626906, -1.08059436, -2.5955867 ]])

In [32]:
data[ [1, 2], : ]

array([[ 1.0943617 ,  0.80581683,  1.70927155],
       [ 1.18626906, -1.08059436, -2.5955867 ]])

In [33]:
data[[4, 2, 6], [2, 1, 0]]

array([ 0.43459118, -1.08059436, -0.45622233])

Más ejemplos:

<img src="../img/index1.png" alt="Drawing" style="width: 500px;"/>

(Fuente: Scipy lectures)

También hay algunas funciones que acceden a determinadas partes de una matriz, por ejemplo:

In [34]:
# diagonal de la matriz
np.diag(data)

array([-1.42597456,  0.80581683, -2.5955867 ])

##### Reducciones

Hacen una operación sobre los miembros del array, devolviendo típicamente un único valor o un array más pequeño

Tutorial: http://www.scipy-lectures.org/intro/numpy/operations.html

In [35]:
a = np.arange(10)
a.sum()

45

In [36]:
x = np.array([[1, 1, 1], [2, 3, 6]])
x

array([[1, 1, 1],
       [2, 3, 6]])

In [37]:
x.sum()

14

In [38]:
x.sum(axis=0)

array([3, 4, 7])

In [39]:
x.sum(axis=1)

array([ 3, 11])

In [40]:
# Media
x.mean()

2.3333333333333335

In [41]:
x.max()

6

In [42]:
x.argmax()

5

In [43]:
c = np.array([1, 0, 0, 0], dtype=bool)
c.any()

True

In [44]:
c.all()

False

La mayoría de estas funciones están implementadas como métodos y como funciones, por ejemplo:

In [45]:
np.var(x)

3.222222222222222

In [46]:
x.var()

3.222222222222222

##### Ejercicio cuadrado mágico

##### Álgebra lineal

Numpy tiene las rutinas básicas para el cálculo de operaciones de álgebra lineal. Estas rutinas son muy eficientes, ya que están implementadas en C (al igual que toda la librería).

Lista: http://docs.scipy.org/doc/numpy-1.15.0/reference/routines.linalg.html

In [47]:
from numpy.linalg import inv

c = np.ones((3, 3))

# producto elemento a elemento
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# producto de matrices (ahora si)
c.dot(c)

#c @ c

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [49]:
# el número de columnas de la primera matriz tiene que coincidir con el número de filas de la segunda
a = np.ones((5, 2))
b = np.ones((2, 3))

a.dot(b).shape

(5, 3)

Hay funciones para calcular la inversa, el determinante, la traza, autovalores, autovectores, etc.

##### Manipular la forma del array

In [50]:
# hacer plano el array
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [52]:
# transpuesta
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [54]:
a.T.reshape((2, 3))

array([[1, 4, 2],
       [5, 3, 6]])

In [55]:
b = np.arange(30)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
c = b.reshape((5, 3, 2))
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [57]:
# con -1 se infiere el tamaño de una dimensión
c.reshape((5, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
c.shape

(5, 3, 2)

In [59]:
# cambiar de orden las dimensiones (generaliza .T)
d = c.transpose((1, 2, 0))
d

array([[[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25]],

       [[ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27]],

       [[ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]]])

In [60]:
d.shape

(3, 2, 5)

In [61]:
# añadir una dimensión
a = np.arange(10)

# por defecto los vectores son vectores columna
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# no es lo mismo esto...
a.shape

(10,)

In [63]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
# que esto...
a[:, None].shape

(10, 1)

In [65]:
# es importante tenerlo en cuenta a la hora de concatenar arrays
import numpy as np
a = np.arange(10)
b = np.arange(2)

In [66]:
np.concatenate((a, b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [67]:
c = np.random.randn(10, 2)
c

array([[ 1.02228428, -1.61048997],
       [ 0.52420195, -0.31625744],
       [-1.51255814,  0.22753394],
       [-0.91559905, -1.04465818],
       [-1.68486371, -0.49575676],
       [-0.66196053,  0.71293954],
       [-1.69974323,  0.5321046 ],
       [ 0.67883926, -0.37392355],
       [-0.49187562,  0.11288697],
       [-0.13619264,  0.07987653]])

In [68]:
a.shape

(10,)

In [69]:
c.shape

(10, 2)

In [70]:
print(a[:, None].shape)
np.concatenate((a[:, None], c), axis=1)

(10, 1)


array([[ 0.        ,  1.02228428, -1.61048997],
       [ 1.        ,  0.52420195, -0.31625744],
       [ 2.        , -1.51255814,  0.22753394],
       [ 3.        , -0.91559905, -1.04465818],
       [ 4.        , -1.68486371, -0.49575676],
       [ 5.        , -0.66196053,  0.71293954],
       [ 6.        , -1.69974323,  0.5321046 ],
       [ 7.        ,  0.67883926, -0.37392355],
       [ 8.        , -0.49187562,  0.11288697],
       [ 9.        , -0.13619264,  0.07987653]])

In [71]:
np.concatenate((a[:, None], c), axis=1)

array([[ 0.        ,  1.02228428, -1.61048997],
       [ 1.        ,  0.52420195, -0.31625744],
       [ 2.        , -1.51255814,  0.22753394],
       [ 3.        , -0.91559905, -1.04465818],
       [ 4.        , -1.68486371, -0.49575676],
       [ 5.        , -0.66196053,  0.71293954],
       [ 6.        , -1.69974323,  0.5321046 ],
       [ 7.        ,  0.67883926, -0.37392355],
       [ 8.        , -0.49187562,  0.11288697],
       [ 9.        , -0.13619264,  0.07987653]])

In [72]:
np.hstack((a[:, None], c))

array([[ 0.        ,  1.02228428, -1.61048997],
       [ 1.        ,  0.52420195, -0.31625744],
       [ 2.        , -1.51255814,  0.22753394],
       [ 3.        , -0.91559905, -1.04465818],
       [ 4.        , -1.68486371, -0.49575676],
       [ 5.        , -0.66196053,  0.71293954],
       [ 6.        , -1.69974323,  0.5321046 ],
       [ 7.        ,  0.67883926, -0.37392355],
       [ 8.        , -0.49187562,  0.11288697],
       [ 9.        , -0.13619264,  0.07987653]])

In [75]:
print(b)
np.concatenate((b, c), axis=0)

[0 1]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [76]:
np.vstack((b, c))

array([[ 0.        ,  1.        ],
       [ 1.02228428, -1.61048997],
       [ 0.52420195, -0.31625744],
       [-1.51255814,  0.22753394],
       [-0.91559905, -1.04465818],
       [-1.68486371, -0.49575676],
       [-0.66196053,  0.71293954],
       [-1.69974323,  0.5321046 ],
       [ 0.67883926, -0.37392355],
       [-0.49187562,  0.11288697],
       [-0.13619264,  0.07987653]])

In [77]:
# con concatenate esto es mas complicado
b.shape

(2,)

In [78]:
c.shape

(10, 2)

In [79]:
b[None, :].shape

(1, 2)

In [80]:
np.concatenate((b[None, :], c), axis=0)

array([[ 0.        ,  1.        ],
       [ 1.02228428, -1.61048997],
       [ 0.52420195, -0.31625744],
       [-1.51255814,  0.22753394],
       [-0.91559905, -1.04465818],
       [-1.68486371, -0.49575676],
       [-0.66196053,  0.71293954],
       [-1.69974323,  0.5321046 ],
       [ 0.67883926, -0.37392355],
       [-0.49187562,  0.11288697],
       [-0.13619264,  0.07987653]])

In [81]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

##### Ejercicio matrices

##### Lectura de ficheros

Con Numpy es muy sencillo escribir y leer ficheros de texto estructurados:

In [82]:
import numpy as np
a = np.random.randn(10, 5)
np.savetxt("rand.csv", a, delimiter=",")

In [83]:
b = np.loadtxt("rand.csv", delimiter=",")
b

array([[-1.64368971, -2.52709246,  0.16498604,  2.27705321, -1.23780884],
       [-1.02568354, -1.88742423, -0.71645719,  0.12089224,  0.78379755],
       [ 1.19519043,  0.55009332,  0.66103268,  0.66025839, -0.37928276],
       [-0.16953404, -0.57288374, -1.69672695,  0.41112141, -1.57771917],
       [-1.39399728,  0.04691074, -0.84241613,  1.48864479,  1.58586327],
       [ 0.34912524,  2.45620722,  0.71662551, -0.74434801,  0.76037839],
       [-1.44705244, -0.51582513, -0.26936855,  0.69026604,  0.76611577],
       [-0.64969548,  0.7705635 ,  0.25497299,  0.10377039, -0.26464955],
       [ 0.59975366, -0.96857547, -0.50156775, -0.19999023, -0.4203457 ],
       [-0.18458233,  0.38748392, -1.52193701,  1.42804694, -2.05090515]])

In [ ]:
def logical2num(s):
    if s == "T":
        return 1
    else:
        return 0
    
np.loadtxt("myfile.csv", delimiter = ",", converters={10: logical2num})

Referencia: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.loadtxt.html

##### Ordenación, búsqueda y conteo

Referencia: https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.sort.html

In [85]:
# ordenación con copia
a = np.random.randn(10)
a

array([ 0.18397693, -1.47135256, -0.33359433,  0.4606704 ,  0.08224995,
        1.03885786,  0.85040036,  0.2434044 , -0.05376677, -0.99351563])

In [86]:
np.sort(a)

array([-1.47135256, -0.99351563, -0.33359433, -0.05376677,  0.08224995,
        0.18397693,  0.2434044 ,  0.4606704 ,  0.85040036,  1.03885786])

In [87]:
a

array([ 0.18397693, -1.47135256, -0.33359433,  0.4606704 ,  0.08224995,
        1.03885786,  0.85040036,  0.2434044 , -0.05376677, -0.99351563])

In [88]:
# ordenacion sin copia
a.sort()
a

array([-1.47135256, -0.99351563, -0.33359433, -0.05376677,  0.08224995,
        0.18397693,  0.2434044 ,  0.4606704 ,  0.85040036,  1.03885786])

In [89]:
# indices donde se cumple una condicion (aplana el array primero)
np.flatnonzero(a < 0)

array([0, 1, 2, 3])

In [90]:
# para arrays multidimensionales
b = np.random.randn(10, 5)
b

array([[ 2.24250767e-01, -2.97840506e-04, -8.94522758e-01,
         7.71151951e-03,  1.10303403e+00],
       [-2.73598018e-01, -1.05366132e+00, -7.48347342e-01,
        -2.04286093e+00, -5.48933195e-01],
       [-1.56796271e-01,  3.58919035e-01,  1.28867824e+00,
         4.50588739e-01, -1.91203026e+00],
       [ 1.16736283e+00, -8.51446596e-02,  1.30077223e+00,
         7.54454503e-01,  3.08025099e-02],
       [ 1.58828110e-01, -1.71321638e+00, -2.44824201e+00,
         1.72902240e+00,  4.48468163e-01],
       [-9.22270601e-01, -1.02256044e+00,  4.57536993e-01,
        -7.66416069e-01, -1.70365122e+00],
       [ 2.11781811e+00,  4.47979296e-01,  2.10920084e+00,
         6.65665465e-01, -3.68779472e-01],
       [-6.50934778e-01,  1.15930273e+00, -1.05392247e+00,
         5.28092098e-01,  1.56097260e+00],
       [-1.42568823e+00, -2.61312648e-01, -2.33299042e-02,
        -1.76662860e+00,  7.57550349e-01],
       [-1.51190795e+00, -2.46295416e-01, -9.15536646e-01,
        -1.79539622e+00

In [91]:
b[ b > 0 ]

array([0.22425077, 0.00771152, 1.10303403, 0.35891903, 1.28867824,
       0.45058874, 1.16736283, 1.30077223, 0.7544545 , 0.03080251,
       0.15882811, 1.7290224 , 0.44846816, 0.45753699, 2.11781811,
       0.4479793 , 2.10920084, 0.66566547, 1.15930273, 0.5280921 ,
       1.5609726 , 0.75755035])

In [92]:
idx = np.nonzero(b > 0)
idx

(array([0, 0, 0, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 6, 6, 6, 6, 7, 7, 7, 8]),
 array([0, 3, 4, 1, 2, 3, 0, 2, 3, 4, 0, 3, 4, 2, 0, 1, 2, 3, 1, 3, 4, 4]))

In [93]:
b[idx]

array([0.22425077, 0.00771152, 1.10303403, 0.35891903, 1.28867824,
       0.45058874, 1.16736283, 1.30077223, 0.7544545 , 0.03080251,
       0.15882811, 1.7290224 , 0.44846816, 0.45753699, 2.11781811,
       0.4479793 , 2.10920084, 0.66566547, 1.15930273, 0.5280921 ,
       1.5609726 , 0.75755035])

In [94]:
# elige elementos de un array u otro dependiendo de la condicion
c = np.where(b < 0, 0, b)
c

array([[0.22425077, 0.        , 0.        , 0.00771152, 1.10303403],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.35891903, 1.28867824, 0.45058874, 0.        ],
       [1.16736283, 0.        , 1.30077223, 0.7544545 , 0.03080251],
       [0.15882811, 0.        , 0.        , 1.7290224 , 0.44846816],
       [0.        , 0.        , 0.45753699, 0.        , 0.        ],
       [2.11781811, 0.4479793 , 2.10920084, 0.66566547, 0.        ],
       [0.        , 1.15930273, 0.        , 0.5280921 , 1.5609726 ],
       [0.        , 0.        , 0.        , 0.        , 0.75755035],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [95]:
# contar no zeros
np.count_nonzero(c)

22

In [96]:
# eliminar repeticiones
np.unique([1, 2, 2, 2, 2, 3, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

##### Muestreos aleatorios

Numpy contiene múltiples funciones para generar números aleatorios con varias distribuciones de probabilidad

Referencia: https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.random.html

In [97]:
# distribucion uniforme en [0, 1]
np.random.rand(10)

array([0.03920324, 0.66309864, 0.91644881, 0.81227021, 0.64676003,
       0.57549556, 0.01234308, 0.46381973, 0.0307049 , 0.66722003])

In [98]:
# distribucion normal
np.random.randn(3, 2)

array([[-0.46521582, -1.77332416],
       [-1.98938299,  1.10304554],
       [-0.07196895, -0.7915928 ]])

In [99]:
# simular 10 tiradas de un dado
np.random.choice(range(6), size=10)

array([3, 1, 5, 5, 2, 1, 1, 2, 5, 3])

##### Broadcasting

* Las operaciones entre arrays se realizan en general elemento a elemento
* Por tanto, los arrays tiene que tener las mismas dimensiones
* Esta regla se relaja en ocasiones, permitiendo operar con dos arrays de distintos tamaños
* En esos casos se promociona al array más pequeño para que tenga el tamaño del grande

Regla de broadcasting: para que se pueda operar con dos arrays de distinto tamaño tienen que coincidir en su última dimensión, o una de las dos ser 1

Referencia: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [100]:
a = np.array([[ 0.0, 0.0, 0.0], [10.0,10.0,10.0], [20.0,20.0,20.0], [30.0,30.0,30.0]])
b = np.array(([1, 2, 3]))

a.shape

(4, 3)

In [101]:
b.shape

(3,)

In [102]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [103]:
c = np.array([4, 5, 6, 7])

In [104]:
a.shape

(4, 3)

In [105]:
c.shape

(4,)

In [106]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [107]:
a + c[:, None]

array([[ 4.,  4.,  4.],
       [15., 15., 15.],
       [26., 26., 26.],
       [37., 37., 37.]])

In [108]:
c[:, None].shape

(4, 1)

In [109]:
d = np.arange(5)
d.shape

(5,)

In [110]:
c + d

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [111]:
c

array([4, 5, 6, 7])

In [112]:
d

array([0, 1, 2, 3, 4])

In [113]:
c[:, None] + d

# 4 4 4 4 4
# 5 5 5 5 5
# 6 6 6 6 6
# 7 7 7 7 7

# 0 1 2 3 4
# 0 1 2 3 4
# 0 1 2 3 4
# 0 1 2 3 4

array([[ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

<img src="../img/broadcast.png" alt="Drawing" style="width: 500px;"/>

(Fuente: Scipy lectures)